project:
  type: book
  output-dir: docs

book:
  title: "Machine Learning"
  # author: "Phil Chodrow"
  # date: "01/25/2026"
  chapters:
    - index.qmd
    - part: "Machine Learning Fundamentals"
      chapters:
      - chapters/02-signal-noise.qmd
      - chapters/03-maximum-likelihood.qmd
      - chapters/04-more-gradients.qmd
      - chapters/06-regularization.qmd
      - chapters/07-bias-variance.qmd
    - part: "Classification"
      chapters: 
      - chapters/10-intro-classification.qmd
      - chapters/15-multinomial-classification.qmd
  body-footer: |
        <br> <br> <span style="color:grey;">&#169; Phil Chodrow, 2025</span>
  sidebar: 
    search: false

format:
  html:
    theme: [cosmo, assets/custom.scss]
    css: assets/styles.css
    number-depth: 0
    reference-location: margin
    callout-icon: false;
    callout-appearance: minimal
    fig-cap-location: margin
    highlight-style: atom-one
    title-block: none
    grid:
      margin-width: 350px
    
jupyter: cs451


execute: 
  cache: true

mermaid: 
  theme: neutral

bibliography: refs.bib

custom-callout:
  sol:
    icon-symbol: "üìù"
    color: "pink"
  question:
    icon-symbol: "‚ùì"
    color: "lightblue"
filters:
- custom-callout
- scripts/collapse-solution-callout.lua
